let handler = async (m, { text }) => {
    const absurdKhodams = [
        { name: "Ambatukam", description: "berarti kamu orang yang selalu berhati-hati dan penuh perhitungan." },
        { name: "Ambatron", description: "berarti kamu penuh energi dan selalu siap bertindak." },
        { name: "Mas Amba", description: "berarti kamu bijaksana dan selalu memberikan nasihat yang tepat." },
        { name: "Mas Rusdi", description: "berarti kamu tegas dan memiliki kepribadian yang kuat." },
        { name: "Mas Kumalala", description: "berarti kamu memiliki semangat juang yang tinggi dan tidak mudah menyerah." },
        { name: "Raja Sigma", description: "berarti kamu penguasa yang memiliki kebijaksanaan yang mendalam." },
        { name: "Suki Liar", description: "berarti kamu bebas dan tidak terikat aturan." },
        { name: "Raja Kegelapan", description: "berarti kamu memiliki daya tarik yang misterius dan memikat." },
        { name: "Hitam Legam", description: "berarti kamu selalu punya sisi gelap yang menarik perhatian." },
        { name: "Kai Cenat", description: "berarti kamu orang yang gesit dan selalu tahu apa yang harus dilakukan." },
        { name: "I Show Speed", description: "berarti kamu cepat tanggap dan selalu siap beraksi dengan cepat." },
        { name: "Fanum Tax", description: "berarti kamu penuh kreativitas dan memiliki gaya unik dalam segala hal." },
        { name: "Gyat Level 1-20", description: "berarti kamu orang yang terus berkembang dan selalu belajar hal baru." },
        { name: "Skibidi Level 1-20", description: "berarti kamu selalu penuh semangat dan siap menghadapi tantangan." },
        { name: "Kulkas", description: "berarti kamu selalu dingin dan tenang dalam menghadapi situasi." },
        { name: "Air Conditioner", description: "berarti kamu selalu memberikan kesejukan dan kenyamanan bagi orang lain." },
        { name: "Galon", description: "berarti kamu selalu penuh energi dan siap memberikan yang terbaik." },
        { name: "Tabung Gas", description: "berarti kamu kuat dan penuh daya tahan dalam menghadapi tekanan." },
        { name: "Toples", description: "berarti kamu selalu rapi dan terorganisir dalam segala hal." },
        { name: "Yakult", description: "berarti kamu menyegarkan dan selalu memberikan energi positif." },
        { name: "Keyboard", description: "berarti kamu cepat dalam merespon dan komunikatif." },
        { name: "Processor", description: "berarti kamu pintar dan selalu memiliki solusi untuk setiap masalah." },
        { name: "Mediatek", description: "berarti kamu canggih dan selalu mengikuti perkembangan teknologi." },
        { name: "Zeus77", description: "berarti kamu penguasa yang perkasa dan penuh keberanian." },
        { name: "Kipas Angin", description: "berarti kamu selalu memberikan kesegaran dan udara segar bagi orang lain." },
        { name: "Badut", description: "berarti kamu penuh humor dan selalu membuat orang tertawa." },
        { name: "Monyet Gila", description: "berarti kamu sangat lincah dan cerdas dalam setiap tindakan." },
        { name: "Kuda Domba", description: "berarti kamu penuh daya kreatifitas yang besar dan selalu menciptakan hal baru." },
        { name: "Superman", description: "berarti kamu penuh dengan kekuatan yang luar biasa dan selalu siap membantu orang lain." },
        { name: "Naruto Uzumaki", description: "berarti kamu orang yang memiliki semangat juang tinggi dan selalu berusaha untuk menjadi yang terbaik." },
        { name: "Spongebob Squarepants", description: "berarti kamu selalu ceria dan penuh semangat dalam menghadapi segala rintangan." },
        { name: "Patrick Star", description: "berarti kamu orang yang penuh dengan kehangatan dan selalu membuat suasana menjadi lebih ceria." },
        { name: "Mr. Bean", description: "berarti kamu orang yang unik dan selalu bisa membuat orang tertawa dalam situasi apa pun." },
        { name: "Gundala Putra Petir", description: "berarti kamu penuh dengan keadilan dan selalu berjuang untuk kebenaran." },
        { name: "Si Doel Anak Betawi", description: "berarti kamu orang yang memiliki kejujuran tinggi dan selalu setia pada nilai-nilai budaya." },
        { name: "Tukul Arwana", description: "berarti kamu memiliki kecerdasan yang tinggi dan selalu memberikan pendapat yang tajam." },
        { name: "Ratna Listy", description: "berarti kamu orang yang penuh pesona dan selalu memiliki pengaruh besar terhadap orang lain." },
        { name: "Bebek Belur", description: "berarti kamu orang yang tidak pernah menyerah dan selalu bangkit kembali setelah mengalami kegagalan." },
        { name: "Doraemon", description: "berarti kamu selalu memberikan solusi cerdas dan kreatif untuk mengatasi masalah." },
        { name: "Nobi Nobita", description: "berarti kamu memiliki ketekunan yang tinggi dan selalu berusaha keras untuk mencapai impianmu." },
        { name: "Shinchan", description: "berarti kamu selalu jujur dan memiliki kepolosan yang menghibur." },
        { name: "Kopral Oswald", description: "berarti kamu penuh dedikasi dan selalu siap membela yang lemah." },
        { name: "Paddle Pop", description: "berarti kamu penuh petualangan dan selalu berani menghadapi bahaya." },
        { name: "Pak Tani", description: "berarti kamu orang yang rendah hati dan selalu bekerja keras untuk mencapai tujuan." },
        { name: "Emak-Emak", description: "berarti kamu memiliki kekuatan luar biasa dalam menjaga keluarga dan lingkungan." },
        { name: "Gepeng", description: "berarti kamu orang yang selalu cerdik dan penuh dengan ide kreatif." },
        { name: "Detektif Conan", description: "berarti kamu orang yang cerdas dan selalu berhasil mengungkap misteri." },
        { name: "Heboh Susanto", description: "berarti kamu selalu menyebarkan keceriaan dan membuat suasana menjadi lebih hidup." },
        { name: "Si Unyil", description: "berarti kamu memiliki semangat persahabatan yang tinggi dan selalu menyenangkan hati orang lain." },
        { name: "Buto Ijo", description: "berarti kamu memiliki keberanian yang luar biasa dan selalu siap melawan kejahatan." },
        { name: "Surti Penjaga Satwa", description: "berarti kamu penuh kasih sayang dan selalu peduli terhadap makhluk hidup." },
        { name: "Mbah Surip", description: "berarti kamu penuh kebijaksanaan dan selalu memberikan inspirasi bagi orang lain." },
        { name: "Mbah Mijan", description: "berarti kamu memiliki intuisi yang kuat dan mampu memprediksi hal-hal yang akan terjadi." },
        { name: "Bang Jarwo", description: "berarti kamu orang yang tangguh dan selalu siap bertarung." },
        { name: "Upin Ipin", description: "berarti kamu orang yang penuh keceriaan dan selalu bisa membuat orang tersenyum." },
        { name: "Pak Raden", description: "berarti kamu orang yang selalu bijaksana dalam memberikan nasihat dan petuah." },
        { name: "Bu Raden", description: "berarti kamu penuh kelembutan dan selalu memberikan kasih sayang kepada orang di sekitarmu." },
        { name: "Bule Betawi", description: "berarti kamu orang yang sangat eksentrik dan selalu tampil beda dari yang lain." },
        { name: "Pisang Goreng", description: "berarti kamu orang yang selalu membuat suasana menjadi lebih hangat dan ramah." },
        { name: "Kue Cubit", description: "berarti kamu selalu menyenangkan dan bisa menghibur siapa saja yang berada di sekitarmu." },
        { name: "Es Cincau", description: "berarti kamu orang yang menyegarkan dan selalu memberikan kesegaran bagi orang lain." },
        { name: "Sate Ayam", description: "berarti kamu orang yang selalu memberikan kenikmatan dan kepuasan bagi orang lain." },
        { name: "Nasi Goreng", description: "berarti kamu orang yang selalu memberikan energi dan semangat kepada orang di sekitarmu." },
        { name: "Ayam Geprek", description: "berarti kamu selalu tegas dan tidak ragu untuk mengejar impianmu." },
        { name: "Martabak Manis", description: "berarti kamu orang yang manis dan selalu bisa membuat orang lain merasa nyaman." },
        { name: "Sambal Penyet", description: "berarti kamu orang yang pedas dan selalu memberikan kejutan dalam setiap tindakanmu." },
        { name: "Bakso Malang", description: "berarti kamu orang yang kuat dan selalu memberikan kepuasan bagi orang lain." },
        { name: "Gado-Gado", description: "berarti kamu orang yang selalu memberikan keharmonisan dan keseimbangan dalam setiap situasi." },
        { name: "Pecel Lele", description: "berarti kamu orang yang kuat dan tangguh dalam menghadapi setiap tantangan." },
        { name: "Es Campur", description: "berarti kamu orang yang unik dan selalu bisa menyatukan berbagai hal menjadi satu kesatuan yang indah." },
        { name: "Kolak Pisang", description: "berarti kamu orang yang penuh kehangatan dan selalu memberikan kebaikan kepada orang di sekitarmu." },
        { name: "Rujak Cingur", description: "berarti kamu orang yang berani dan tidak takut untuk menghadapi hal-hal yang sulit." },
        { name: "Ketoprak", description: "berarti kamu orang yang selalu memberikan keberanian dan inspirasi bagi orang lain." },
        { name: "Es Doger", description: "berarti kamu orang yang menyenangkan dan selalu bisa memberikan kebahagiaan bagi orang lain." },
        { name: "Kerak Telor", description: "berarti kamu orang yang kuat dan tidak mudah terpengaruh oleh lingkungan sekitarmu." },
        { name: "Lontong Balap", description: "berarti kamu orang yang cepat dalam mengambil keputusan dan selalu siap berlomba untuk meraih yang terbaik." },
        { name: "Rawon Setan", description: "berarti kamu orang yang kuat dan tangguh dalam menghadapi setiap rintangan." },
        { name: "Soto Betawi", description: "berarti kamu orang yang penuh keberanian dan selalu siap melindungi yang lemah." },
        { name: "Pempek Palembang", description: "berarti kamu orang yang memiliki keberanian untuk berbeda dan tidak takut untuk menunjukkan identitasmu." },
        { name: "Rendang Padang", description: "berarti kamu orang yang kuat dan penuh ketabahan dalam menghadapi segala hal." },
        { name: "Nasi Kucing", description: "berarti kamu orang yang cerdik dan selalu bisa memanfaatkan setiap kesempatan dengan baik." },
        { name: "Lemper Ayam", description: "berarti kamu orang yang setia dan selalu dapat diandalkan oleh teman-temanmu." },
        { name: "Bubur Ayam", description: "berarti kamu orang yang selalu memberikan kenyamanan dan kehangatan bagi orang lain." },
        { name: "Sop Buntut", description: "berarti kamu orang yang kuat dan tangguh dalam menghadapi segala masalah." },
        { name: "Pisang Epe", description: "berarti kamu orang yang unik dan selalu tampil beda dari yang lain." },
        { name: "Kerak Telor", description: "berarti kamu orang yang kuat dan tidak mudah terpengaruh oleh lingkungan sekitarmu." },
        { name: "Sate Kere", description: "berarti kamu orang yang selalu rendah hati dan tidak sombong meski memiliki prestasi." },
        { name: "Gehu Pedas", description: "berarti kamu orang yang penuh semangat dan selalu memberikan kejutan dalam tindakanmu." },
        { name: "Ayam Goreng", description: "berarti kamu orang yang kuat dan selalu memberikan energi positif kepada orang lain." },
        { name: "Indomie Goreng", description: "berarti kamu orang yang praktis dan selalu bisa menyesuaikan diri di segala situasi." },
        { name: "Martabak Telur", description: "berarti kamu orang yang selalu memberikan kehangatan dan kenyamanan bagi orang lain." },
        { name: "Bakwan Malang", description: "berarti kamu orang yang penuh keberanian dan selalu siap menghadapi tantangan." },
        { name: "Rujak Buah", description: "berarti kamu orang yang selalu bisa menyatukan perbedaan menjadi satu kesatuan yang harmonis." },
        { name: "Es Teler", description: "berarti kamu orang yang penuh keberagaman dan selalu bisa memberikan warna dalam kehidupan orang lain." },
        { name: "Soto Betawi", description: "berarti kamu orang yang penuh keberanian dan selalu siap melindungi yang lemah." },
        { name: "Ayam Geprek", description: "berarti kamu selalu tegas dan tidak ragu untuk mengejar impianmu." },
        { name: "Martabak Manis", description: "berarti kamu orang yang manis dan selalu bisa membuat orang lain merasa nyaman." },
        { name: "Sambal Penyet", description: "berarti kamu orang yang pedas dan selalu memberikan kejutan dalam setiap tindakanmu." },
        { name: "Bakso Malang", description: "berarti kamu orang yang kuat dan selalu memberikan kepuasan bagi orang lain." },
        { name: "Gado-Gado", description: "berarti kamu orang yang selalu memberikan keharmonisan dan keseimbangan dalam setiap situasi." },
        { name: "Pecel Lele", description: "berarti kamu orang yang kuat dan tangguh dalam menghadapi setiap tantangan." },
        { name: "Es Campur", description: "berarti kamu orang yang unik dan selalu bisa menyatukan berbagai hal menjadi satu kesatuan yang indah." },
        { name: "Kolak Pisang", description: "berarti kamu orang yang penuh kehangatan dan selalu memberikan kebaikan kepada orang di sekitarmu." },
        { name: "Rujak Cingur", description: "berarti kamu orang yang berani dan tidak takut untuk menghadapi hal-hal yang sulit." },
        { name: "Ketoprak", description: "berarti kamu orang yang selalu memberikan keberanian dan inspirasi bagi orang lain." },
        { name: "Es Doger", description: "berarti kamu orang yang menyenangkan dan selalu bisa memberikan kebahagiaan bagi orang lain." },
        { name: "Kerak Telor", description: "berarti kamu orang yang kuat dan tidak mudah terpengaruh oleh lingkungan sekitarmu." },
        { name: "Lontong Balap", description: "berarti kamu orang yang cepat dalam mengambil keputusan dan selalu siap berlomba untuk meraih yang terbaik." },
        { name: "Rawon Setan", description: "berarti kamu orang yang kuat dan tangguh dalam menghadapi setiap rintangan." },
        { name: "Soto Betawi", description: "berarti kamu orang yang penuh keberanian dan selalu siap melindungi yang lemah." },
        { name: "Pempek Palembang", description: "berarti kamu orang yang memiliki keberanian untuk berbeda dan tidak takut untuk menunjukkan identitasmu." },
        { name: "Rendang Padang", description: "berarti kamu orang yang kuat dan penuh ketabahan dalam menghadapi segala hal." },
        { name: "Nasi Kucing", description: "berarti kamu orang yang cerdik dan selalu bisa memanfaatkan setiap kesempatan dengan baik." },
        { name: "Lemper Ayam", description: "berarti kamu orang yang setia dan selalu dapat diandalkan oleh teman-temanmu." },
        { name: "Bubur Ayam", description: "berarti kamu orang yang selalu memberikan kenyamanan dan kehangatan bagi orang lain." },
        { name: "Sop Buntut", description: "berarti kamu orang yang kuat dan tangguh dalam menghadapi segala masalah." },
        { name: "Pisang Epe", description: "berarti kamu orang yang unik dan selalu tampil beda dari yang lain." },
        { name: "Sate Kere", description: "berarti kamu orang yang selalu rendah hati dan tidak sombong meski memiliki prestasi." },
        { name: "Gehu Pedas", description: "berarti kamu orang yang penuh semangat dan selalu memberikan kejutan dalam tindakanmu." },
        { name: "Ayam Goreng", description: "berarti kamu orang yang kuat dan selalu memberikan energi positif kepada orang lain." },
        { name: "Indomie Goreng", description: "berarti kamu orang yang praktis dan selalu bisa menyesuaikan diri di segala situasi." },
        { name: "Martabak Telur", description: "berarti kamu orang yang selalu memberikan kehangatan dan kenyamanan bagi orang lain." },
        { name: "Bakwan Malang", description: "berarti kamu orang yang penuh keberanian dan selalu siap menghadapi tantangan." },
        { name: "Rujak Buah", description: "berarti kamu orang yang selalu bisa menyatukan perbedaan menjadi satu kesatuan yang harmonis." },
        { name: "Es Teler", description: "berarti kamu orang yang penuh keberagaman dan selalu bisa memberikan warna dalam kehidupan orang lain." }
    ];

    let chosenKhodam = absurdKhodams[Math.floor(Math.random() * absurdKhodams.length)];
    let message = `Khodam ${chosenKhodam.name} berarti kamu ${chosenKhodam.description}`;

    await conn.sendMessage(m.chat, { text: message }, { quoted: m });
}

handler.command = ['cekkhodam']

module.exports = handler;